"""esquema inicial: usuarios, quinielas, participaciones, partidos, predicciones

Revision ID: 491b3b80d724
Revises: 
Create Date: 2026-06-10 13:56:13.594068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491b3b80d724'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('equipo_local', sa.String(length=60), nullable=False),
    sa.Column('equipo_visitante', sa.String(length=60), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.Column('grupo', sa.String(length=1), nullable=True),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.CheckConstraint('(goles_local IS NULL AND goles_visitante IS NULL) OR (goles_local IS NOT NULL AND goles_visitante IS NOT NULL)', name=op.f('ck_partidos_resultado_completo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partidos')),
    sa.UniqueConstraint('numero', name=op.f('uq_partidos_numero'))
    )
    op.create_index(op.f('ix_partidos_fecha_hora'), 'partidos', ['fecha_hora'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('user', 'admin')", name=op.f('ck_usuarios_rol_valido')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('quinielas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('codigo_invitacion', sa.String(length=9), nullable=False),
    sa.Column('creador_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.id'], name=op.f('fk_quinielas_creador_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quinielas'))
    )
    op.create_index(op.f('ix_quinielas_codigo_invitacion'), 'quinielas', ['codigo_invitacion'], unique=True)
    op.create_index(op.f('ix_quinielas_creador_id'), 'quinielas', ['creador_id'], unique=False)
    op.create_table('participaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('quiniela_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiniela_id'], ['quinielas.id'], name=op.f('fk_participaciones_quiniela_id_quinielas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_participaciones_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participaciones')),
    sa.UniqueConstraint('usuario_id', 'quiniela_id', name=op.f('uq_participaciones_usuario_id'))
    )
    op.create_index(op.f('ix_participaciones_quiniela_id'), 'participaciones', ['quiniela_id'], unique=False)
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participacion_id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('goles_local BETWEEN 0 AND 20 AND goles_visitante BETWEEN 0 AND 20', name=op.f('ck_predicciones_goles_rango')),
    sa.ForeignKeyConstraint(['participacion_id'], ['participaciones.id'], name=op.f('fk_predicciones_participacion_id_participaciones')),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], name=op.f('fk_predicciones_partido_id_partidos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predicciones')),
    sa.UniqueConstraint('participacion_id', 'partido_id', name=op.f('uq_predicciones_participacion_id'))
    )
    op.create_index(op.f('ix_predicciones_partido_id'), 'predicciones', ['partido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predicciones_partido_id'), table_name='predicciones')
    op.drop_table('predicciones')
    op.drop_index(op.f('ix_participaciones_quiniela_id'), table_name='participaciones')
    op.drop_table('participaciones')
    op.drop_index(op.f('ix_quinielas_creador_id'), table_name='quinielas')
    op.drop_index(op.f('ix_quinielas_codigo_invitacion'), table_name='quinielas')
    op.drop_table('quinielas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_partidos_fecha_hora'), table_name='partidos')
    op.drop_table('partidos')
    # ### end Alembic commands ###
